[package]
name = "nocuous"
version = "1.1.0"
edition = "2021"
description = "Wasm bindings to peform static analysis of JavaScript and TypeScript code"
authors = ["Kitson P. Kelly"]
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]
name = "nocuous"

[dependencies]
anyhow = "1.0.75"
deno_ast = { version = "0.42.1", features = ["cjs", "dep_analysis", "view", "visit"] }
futures = "0.3.28"
import_map = "0.20.1"
indexmap = { version = "2.0.0", features = ["serde"] }
js-sys = "0.3.64"
lazy_static = "1.4.0"
regex = "1.9.4"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
url = "2.4.1"
wasm-bindgen = { version = "=0.2.92", features = ["serde-serialize"] }
wasm-bindgen-futures = "=0.4.42"

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "s"
