name: ci

on: [push, pull_request]

jobs:
  nocuous:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.x, canary]
    steps:
      - name: clone repository
        uses: actions/checkout@v4
      
      - name: install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache
        uses: Swatinem/rust-cache@v1

      - name: install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.version }}
      
      - name: format
        run: |
          cargo fmt -- --check
          deno fmt --check
      
      - name: lint
        run: |
          cargo clippy --locked --release --all-features --all-targets
          deno lint

      - name: build
        run: cargo build

      - name: test
        run: deno task test

      - name: check wasm build
        run: deno task build --check
